### ISSUE TITLE
random crash

### ISSUE THREAD

**Issue by popcorn9499** [popcorn9499/irc-discord#11]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "ircDiscordRelay.py", line 151, in on_ready
    await discordCheckMsg()
  File "ircDiscordRelay.py", line 124, in discordCheckMsg
    await discordSendMsg(msg) #sends message
  File "ircDiscordRelay.py", line 117, in discordSendMsg
    await client.send_message(channelToUse, msg) #sends the message to the channel specified in the beginning
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 1152, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild_id, tts=tts, embed=embed)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 211, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: INTERNAL SERVER ERROR (status code: 500): errors={'10.10.0.97': 'Client request timeout. See Session.execute[_async](timeout)'}, last_host=10.10.0.97

**Comment by popcorn9499** [comment]
it would do the discord to irc side of things but irc to discord doesnt work. that was the error that was on the bot window last i checked it

**Comment by popcorn9499** [comment]
that crash before seems to be unrelated but the one ive seen alot is irc disconnecting the discord bot normally runs fine.

> ERROR:MyClient:popicraft:Encountered error on socket.
TimeoutError: Ping timeout: no data received from server in 300 seconds.
ERROR:MyClient:popicraft:Unexpected disconnect. Giving up.


So im thinking that im going to have to either look into why this occured which i think is semi obvious but also look into making the bot reconnect on socket errors and not break all the things

**Comment by popcorn9499** [comment]
Seems i fixed my random crashing. this then caused another error.
 

> Exception ignored in: <bound method EventLoop.__del__ of <pydle.async.EventLoop object at 0x7fbdb0ae3358>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pydle/async.py", line 113, in __del__
  File "/usr/local/lib/python3.5/dist-packages/tornado/ioloop.py", line 713, in close
  File "/usr/local/lib/python3.5/dist-packages/tornado/platform/posix.py", line 48, in fileno
ValueError: I/O operation on closed file
Exception in thread Thread-3639:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "ircDiscordRelay.py", line 290, in start
    ircClient.connect(ircServerIP) ##add a option for /pass user:pass this is how znc lets u login
  File "/usr/local/lib/python3.5/dist-packages/pydle/features/tls.py", line 37, in connect
    return super().connect(hostname, port, tls=tls, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pydle/features/rfc1459/client.py", line 190, in connect
    super().connect(hostname, port, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pydle/client.py", line 103, in connect
    self._connect(hostname=hostname, port=port, reconnect=reconnect, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pydle/features/tls.py", line 56, in _connect
    self.connection.connect()
  File "/usr/local/lib/python3.5/dist-packages/pydle/connection.py", line 72, in connect
    self.socket = socket.create_connection((self.hostname, self.port), timeout=self.CONNECT_TIMEOUT, source_address=self.source_address)
  File "/usr/lib/python3.5/socket.py", line 693, in create_connection
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
OSError: [Errno 24] Too many open files

**Comment by popcorn9499** [comment]
hopefully fixed so im gonna close this. https://github.com/popcorn9499/irc-discord/commit/db492aed069f7ecc7ce9151155813d7349116697 should of fixed it.
